### ISSUE TITLE
Figures 1-2

### ISSUE THREAD

**Issue by jcvdav** [oharac/spp_health_dists#1]
Figured I'd start using issues instead of going back and forth on emails.

Original message from @oharac:

> Here's a rough draft for figure 1, below; the code is here (pushed to Github): https://github.com/oharac/spp_risk_dists/blob/master/figs_1_2_maps.Rmd.  It would be cool if the color bar from the maps lined up exactly with the y axis of the density plots, such that they become one and the same (and then the labels on the map color bar become the labels on the density plot y axis).  Also not sure if there are good ways to shift the panel labels; the B and D labels would be better right justified to get them out of the way.  (Or if the map and density plots look really cohesive, maybe it becomes just A (top row) and B (bottom row)?)
>
>Anyway, figured you might have some tricks up your sleeve for getting that color bar up against the density plot.  If not, no biggie, I like this kind of stuff and happy to keep messing with it.

![image](https://user-images.githubusercontent.com/11950459/42653431-543facda-85ca-11e8-8a22-dda7781f4e2d.png)

**Comment by jcvdav** [comment]
This is what I was able to do:

![image](https://user-images.githubusercontent.com/11950459/42653484-6f3c8d6e-85ca-11e8-9e10-1f09ba853155.png)

The blank space between the colorbar and the image is caused by the `element_blank()` in the `x.axis.text` and `x.axis.title` before the `coord_flip()`. I believe it can be minimized by setting these values to `element_text(size = 0)`  and increasing colorbar width from 0.5 to 1 or somehing like that.

If this looks good, I'll modify the `four_panel` so that it produces this figure.

**Comment by oharac** [comment]
cool - what's the code to stretch the color bar to the full height of the density plot?

I ended up trying a totally different approach to the color bar, basically making a gradient along the left side of the density plots, using the same color scale/breaks/labels, so it's built-in to the density plot instead of the map.  (I needed a little more procrastination time...)

![image](https://user-images.githubusercontent.com/10714327/42701748-4091b086-867c-11e8-86c0-e65794c7cd35.png)

Still needs a little work on the margins, A/B labels, etc but I think it's pretty nice.

**Comment by jcvdav** [comment]
Nice! I think these look way better, and it is much more intuitive to have the colorbar right on the axis.

To control width and height of the colorbar, I used

```
plot  +
  guides(fill = guide_colorbar(barwidth = 1,
                               barheight = 10,
                               frame.colour = "black",
                               ticks.colour = "black"))
```
