### ISSUE TITLE
figure 4 - fisheries

### ISSUE THREAD

**Issue by oharac** [oharac/spp_health_dists#2]
sorry @jcvdav - hit enter too fast and left the comment blank at first.  I'm thinking the fishing effort maps are more interesting in general for the main manuscript - the scatter plots are great but maybe can go in the supplemental - maybe a global one would be cool for the manuscript if you can work it into a single figure with maps? 

Can you take a crack at fine tuning a solid figure 4?

I think this map rocks (and the corresponding one for high values):
![image](https://user-images.githubusercontent.com/10714327/42702023-0ec02e9c-867d-11e8-81bc-8eda7eaaf652.png)

Since I'm redoing the calcs and maps based on equal area Gall-Peters 10 km^2^ cells, we need to figure out a reasonable low threshold based on the fishing *intensity* (effort per area, i.e. hr yr^-1^ km^-2^ (or per 10-km^2^ cell)) and similar for high, based on something close to the bottom 10% and top 10% like you did for the 0.10° cells.  

* the low effort map covers a huge area - is this also including cells with zero effort?  otherwise it should be only covering 10% of the map.  Maybe there's a way to distinguish *low* effort from *zero* effort, either by separating maps (one for zero effort, one for low) or using alpha or shading to differentiate zero from low?
* The high effort map is super sparse, so maybe expand the range so there are more cells? maybe top 25%?
* I threw some grey background to help distinguish the light yellow from the otherwise white background but there are probably better solutions...

What about a four-panel? that could work for the aspect ratio of the maps.  One panel = global scatter, one panel each of zero effort, low effort, high effort? 

or maybe a three panel, one global scatter, one zero and low effort combined, one high effort, but the aspect ratio of the maps makes this a tall figure.

**Comment by jcvdav** [comment]
Sorry @oharac, due to last week's migration from umail to Gmail my inbox was a mess, and I just saw this today.

I'll work on this tomorrow morning and have a first draft by the end of the day.

**Comment by oharac** [comment]
no problem - I've been in a working group the last couple of days so haven't had much time to do anything on the project the last day or two.  Let me know when you have something good.  It looked like the cutoffs for low and high fishing effort might need to be a little higher to have anything really visible if those are separated out on maps.

I hope to chat with my IUCN contact on Friday so I can get some maps from her soon!

**Comment by jcvdav** [comment]
Hey @oharac, I was going through the repo and saw that you have something for [Fig 4](https://github.com/oharac/spp_risk_dists/blob/master/ms_figures/fig4_fishing_intensity.png). I looked for the script / Rmd that generated it, but couldn't find it, so created one.

You are correct in assuming that the previous figure (the one in your issue description) had NAs and effort < 10%. That's why it appears so widespread. However, we can plot the fishing effort and see that it's not all over the place:

![image](https://user-images.githubusercontent.com/11950459/42916241-13295b1c-8ab9-11e8-96dc-c21e946ffa2b.png)

So the 10th percentile woul only include 10% of these points (cells).


The final figure looks like this, where A) is diversity vs fishing effort, B) is areas with no fishing detected by GFW in 2006, C is the lower 25th percentile, and D) is the top 25th percentile.

![image](https://user-images.githubusercontent.com/11950459/42916287-5b799ef4-8ab9-11e8-856e-9af4cd21f887.png)

A couple of thoughts I have:
- I noted that we lost some data in the reprojection of GFW raster to `cea`. If you give me the parameterization of eastings and northings using in your Gall-Petters, I can calculate them from the raw long - lat data. I tried to, but not sure what value of Earth's radius was used in this case (and reference lat is 45, right?)

- I note that a large portion of "unseen" fishing hours is in the coral triangle. That makes sense, because AIS doesn't have good vocerage ther (few boats have it). However, GFW has VMS data for those regions. I can ask to see if these data are available for research, or are under embargo for GFW - Government utilization only. If they are available, we might as well ask for permission to use them and the 2017 data (a formality, really).
---

I also created some other figures (for us, not even the supplementary materials):

This one shows the distribution of risk for sites with and without fishing
![image](https://user-images.githubusercontent.com/11950459/42916171-b95e0ef2-8ab8-11e8-9854-a88c3fb4b459.png)

This is the distribution of effort, showing the proportion of the data mapped to Fig4C and Fig4C in light and dark, respectively.
![image](https://user-images.githubusercontent.com/11950459/42916202-d3d52a7c-8ab8-11e8-9c37-769cf172ba2c.png)

**Comment by oharac** [comment]
Cool - I was also looking at the data after reprojection and saw some kind of issue but didn't dig in.  Yes, Gall-Peters is just CEA with 45 degrees as the reference latitude.  Here's the proj4string I'm using: 

`+proj=cea +lon_0=0 +lat_ts=45 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs`

I had been looking at it in terms of fishing intensity (effort/area) rather than just effort (since the result is an equal area projection, it's essentially equivalent except a scaling factor).  But to be consistent in the conversion, lat-long data should be converted to intensity, then reprojected.  I think you were doing that anyway, but just confirming.

It would be great to fill those apparent gaps - anyone looking at those areas would be very skeptical of our conclusions otherwise... what's VMS?

Can we get the three maps to use a single color bar to save some real estate?  still trying to figure out the finer points of cowplot!  Also, since we're basically categorizing the values, can it be a discrete legend instead of a continuous color bar?

**Comment by jcvdav** [comment]
I'll try two things.

- First I'll try to convert lat-long to northings-easting, but I'll need to figure out the propper value of R (earth's radius) used to make sure the coordinates match,
![image](https://user-images.githubusercontent.com/11950459/43014964-e5550d8a-8c02-11e8-9d03-dc69f4e0e5ad.png)

- I'll divide fishing hours by the area of each 0.1 deg cell (`raster / area(raster)`), and then reproject

VMS is Vessel Monitoring Systems. It's not broadcasted on open signals, and is usually used by the governments (and not always shared). GFW has Indonesia VMS data. I'll poke to see if it's available.

I'll get you the finalized maps later today, using a single discrete colorbar

**Comment by oharac** [comment]
sweet!  I look forward to seeing (and stealing ideas from) the code.

What are the advantages to the northing/easting method vs. just using `st_transform()`?  I haven't explored down that path.

**Comment by jcvdav** [comment]
How does this look @oharac ?

![image](https://user-images.githubusercontent.com/11950459/43029730-c50dc9d2-8c3d-11e8-8a2e-c7437309bbb0.png)

**Comment by oharac** [comment]
hey - just saw this issue - looks great!  

On A, the bottom axis is log(fishing hours per km^2)?  At what point does hours/km^2 effectively become zero...  seems like we could bump that up to capture hours per 100 km^2 cell (to make the neg exponents a little less negative by 2); and then should there be a threshold below which we just call it zero?  E.g. if log(hours/100 km^2) = -2 (about where the 25%ile looks right now), that's basically 36 seconds of fishing over the course of a year; is that even reasonable to think of as "fishing"?  and there are sooooo many data points below that threshold.

This is more philosophical than anything... just trying to wrap my head around this weird data.

**Comment by jcvdav** [comment]
Oh, I see what you mean. Makes sense, I think using this cutoff would highlight our patterns. I'll play with this after I finish reviewing the paper.
