### ISSUE TITLE
having a hard time getting fisheries to fit...

### ISSUE THREAD

**Issue by oharac** [oharac/spp_health_dists#3]
hey @jcvdav - finally getting the bulk of the additional shapefiles, going back and working on the draft while everything crunches down.  I am having a hard time convincing myself that the fisheries bit is working in this context: it is such a simplified version of fishing effort, ignoring so many of the subtleties of fisheries, that I think it opens up the manuscript to lots of questions and concerns without providing a strong return.  I think fisheries analysis would be better left to a paper specifically focused on that, to really dig into the details, and using this one to focus more on conservation and MPAs. 

I'm happy to keep you on the paper if you're still interested - even leaving out the analysis, fisheries are def worth some text in the discussion, and your perspective has been super helpful on the previous draft.

Also thinking of adding a bit about risk distributions in ecoregions (provinces really) to get a sense of tropics vs temperate etc - something like this plot, a little more geographically organized, with perhaps the total number of spp in each province.  If I remember right you were looking at ecoregions in terms of fishing pressures, maybe you have ideas that could apply to biodiversity as well? OTOH, this is pretty similar to the MPA plot already, just focusing more on biogeophysical regions rather than political regions.

![image](https://user-images.githubusercontent.com/10714327/44216777-9aa4f380-a12a-11e8-9a29-1e86a769ca3f.png)

Thoughts?

**Comment by oharac** [comment]
Rather than MEOW provinces, which are somewhat similar to the georegions I've already got in the MPA plots, I think I'll focus instead on different habitats - here's a first-pass figure:

![image](https://user-images.githubusercontent.com/10714327/44284633-4297eb00-a217-11e8-9179-4a1a7a3ae2f8.png)

**Comment by jcvdav** [comment]
Hi @oharac

Sorry for the delayed response, I've been traveling back from Indonesia and had limited connectivity.

I agree, the fishing activity is not fitting nicely, and we know that biodiversity is at risk due to many more stressors. Talking about fishing would only open the question to all other "cumulative humman impacts".

I think we can talk about the fisheries on my MPA/fisheries paper and hopefully tell a more cohesive story.

If love to still be a part of this. But of course, my contributions should be significant (I'll let you decide what's significant and what's not). I am happy to work on figures, text, or anything else you deem necessary and relevant.

I like the habitat-specific risk distributions (is that rr-weighted?). I think it helps highlight the story of pelagic vs coastal and tropical vs temperate better. Just to fill it with as many aesthetics as possibly, how would that figure look like with fill given by %threatened or other measure? Just throwing ideas.

I'm writing from my phone now, but I'm wondering if it would be interesting to show an EEZ vs high seas one (in the supplements, of course). I can look into that later, when I make a fresh pull from my computer. High seas have little to no governance, and we can add a small paragraph echoing the efforts by Sala, Costello and Sumaila to talk about increasing governance of the high seas and the benefits in terms of risk reduction or sometime along those lines.

**Comment by oharac** [comment]
Based on your comments on the previous draft, I did add a high seas density plot to the georegions no-take vs non-no-take plot, and it's pretty clear that the average risk is higher: 
![image](https://user-images.githubusercontent.com/10714327/44301840-bf3bcf80-a2d2-11e8-8e7d-7115fd734710.png)

Still playing around with the habitat plot - I might do side-by-side of uniform weighting vs rr-weighting similar to the MPA plot.  The risk and pct threatened I think would have to be on separate plots, kinda difficult to capture the pct threatened as a single aesthetic call.  Still playing around with it - I'll work on a new draft and hope to get something to you and everyone by early next week for comments and edits... then I might enlist you to help with figures especially SI stuff.

**Comment by jcvdav** [comment]
This looks great! I think this highlights the "high seas governance" narrative very nicely.

Ok, I'll stand by and wait for further instructions. I just did a fresh pull, but I'll keep an eye on any further commits.
